[package]
name = "notify-rust"
version = "3.3.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>", "panicbit <panicbit@users.noreply.github.com>"]
description = "Show desktop notifications. Pure Rust dbus client and server."
homepage = "https://github.com/hoodie/notify-rust"
repository = "https://github.com/hoodie/notify-rust"
documentation = "https://docs.rs/notify-rust/"

license = "MIT/Apache-2.0"
keywords = ["desktop", "notification", "notify", "dbus", "libnotify"]
readme = "README.md"

include = [
  "History.md",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]


[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
dbus = { version = "~0.4"}

[target.'cfg(target_os="macos")'.dependencies]
mac-notification-sys = "0.1.2"

[features]
default = []
