on: [push]

name: Continuous integration

jobs:
  linux:
    name: Test and Lint (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.44.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - run: sudo apt-get install -y libdbus-1-dev
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run
      - name: test_features_images
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run --features images
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  windows:
    name: Test and Lint (Windows)
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.44.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  macos:
    name: Test and Lint (macos)
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.44.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run
      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
