name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pr_check:
      name: Pull Request Check
      uses: ./.github/workflows/pull-request.yml

  linux:
    name: linux
    needs: pr_check
    runs-on: ubuntu-latest
    strategy:
      #fail-fast: true
      matrix:
        rust:
          - stable
          - beta 
          - stable minus 2 releases
        feature:
          - d
          - d,images
          - z
          - z,images
          - z,d
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - run: sudo apt-get install -y libdbus-1-dev

      - name: check (default features)
        run: cargo check

      - name: check (${{matrix.feature}})
        run: cargo check --no-default-features --features ${{matrix.feature}}

      # - name: test (default features)
      #   run: cargo test

      - name: test lib (${{matrix.feature}})
        run: cargo test --lib --no-default-features --features ${{matrix.feature}}

      # - name: test tests (${{matrix.feature}})
      #   run: cargo test --tests --no-default-features --features ${{matrix.feature}}

      - name: test docs (${{matrix.feature}})
        run: cargo test --doc --no-default-features --features ${{matrix.feature}}

      - name: clippy (default features)
        run: cargo clippy

  windows:
    name: windows
    needs: pr_check
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta 
          - stable minus 6 releases
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: check (default features)
        run: cargo check

      - name: test (default features)
        run: cargo test --no-run

      - name: clippy (default features)
        run: cargo clippy -- -D warnings


  macos:
    name: macos
    needs: pr_check
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta 
          - stable minus 6 releases
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt

      - name: check (default features)
        run: cargo check

      - name: test (default features)
        run: cargo test --no-run

      - name: clippy (default features)
        run: cargo clippy -- -D warnings
